version: 0.2
env:
  parameter-store:
    GITHUB_TOKEN: /github/automation_token
    NPM_TOKEN: /npm/automation_token
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm i
      - npm test
      - |
        if expr "$CODEBUILD_SOURCE_VERSION" = "master" "|" "$CODEBUILD_WEBHOOK_HEAD_REF" = "refs/heads/master"; then
          npm run dist
          ./node_modules/.bin/semantic-release
        fi
